name: cineacademy.us

# 触发条件：在 push 到 master 分支后触发
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: cineacademy.us build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        # 设置 node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build project
        run: npm run-script build

      - name: Deploy cineacademy.us
        env:
          # Github 仓库
          GITHUB_REPO: github.com/bstcine/bstcine.github.io
        # 将编译后的博客文件推送到指定仓库
        run: |
          cd ./dist && git init && git add .
          git config user.name "daweilv"
          git config user.email "lvdawei1970@gmail.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.DAVID_WORKFLOW }}@$GITHUB_REPO" master:master
